version: '3.8'

services:
  pocketbase:
    build: ./docker/pocketbase
    container_name: pointage-alae-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./docker/pocketbase/pb_data:/pb_data
      - ./pocketbase_schema.json:/pb_data/pocketbase_schema.json
    networks:
      - alae-network

networks:
  alae-network:
    driver: bridge